### ISSUE TITLE
Perhaps we should remove this config parameter as well

### ISSUE THREAD

**Issue by gvseghbr** [tengu-team/layer-ssl-termination-client#1]
https://github.com/tengu-team/layer-ssl-termination-client/blob/b531d6d0d585fbfe414166fb5c1eda97c0ff7adc/config.yaml#L7

**Comment by xannz** [comment]
If we remove this config option, basic auth is no longer possible. Is this the desired outcome? 
The ssl-termination-proxy also still has this option for backwards compatibility.
